sudo: false

language: node_js

node_js:
  - "6"

script:
  - npm run test
  - codeclimate-test-reporter < coverage/lcov.info

cache:
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: 00c5fb58ac00b89d8a342c343ddae17abe6f9070f962eccbba5174b4f9a68ea8
